### ISSUE TITLE
What I do wrong?

### ISSUE THREAD

**Issue by RomanEmelyanov** [hackbunny/viramarama#2]
$ python3 viramarama.py 
Traceback (most recent call last):
  File "viramarama.py", line 234, in <module>
    print(chr(consonant1) + chr(script['virama']) + chr(consonant2) + chr(0x200C) + chr(vowel))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)
$

**Comment by hackbunny** [comment]
I think it's trying to encode the characters for console output, but the console doesn't support Unicode. Have you tried redirecting the output to a file? I'm sorry, I don't have a lot of experience with Python 3

**Comment by RomanEmelyanov** [comment]
Thanks!
